dataNodesAreMasterEligible = "Yes"
vmDataNodeCount            = "4"
vmSizeAllNodes             = "Standard_D4s_v3"
storageAccountType         = "Default"
vmDataDiskCount            = "2"
esVersion                  = "6.8.14"
