dataNodesAreMasterEligible = "Yes"
vmDataNodeCount = "3"
vmSizeAllNodes = "Standard_D2_v2"
storageAccountType = "Default"
vmDataDiskCount = "2"
dynatrace_instance = "yrk32651"
dynatrace_hostgroup = "LDATA_CFT"
dynatrace_token = "${data.azurerm_key_vault_secret.dynatrace_token.value}"

aks_infra_subscription_id = "4da0ce99-35c5-491f-8a0b-56c39f7278fa"
