dataNodesAreMasterEligible = "Yes"
vmDataNodeCount            = "3"
vmSizeAllNodes             = "Standard_D2_v2"
storageAccountType         = "Default"
vmDataDiskCount            = "2"
esVersion                  = "6.8.14"
