dataNodesAreMasterEligible = "Yes"
vmDataNodeCount = "4"
vmSizeAllNodes = "Standard_D4s_v3"
storageAccountType = "Default"
vmDataDiskCount = "2"
dynatrace_instance = "yrk32651"
dynatrace_hostgroup = "PERF_CFT"
