dataNodesAreMasterEligible = "Yes"
vmDataNodeCount            = "4"
vmSizeAllNodes             = "Standard_D4s_v3"
storageAccountType         = "Default"
vmDataDiskCount            = "2"
dynatrace_instance         = "ebe20728"
dynatrace_hostgroup        = "PROD_CFT"
