dataNodesAreMasterEligible = "Yes"
vmDataNodeCount = "3"
vmSizeAllNodes = "Standard_D2_v2"
storageAccountType = "Default"
vmDataDiskCount = "2"
dynatrace_instance = "ebe20728"
dynatrace_hostgroup = "PROD_CFT"
dynatrace_token = "${data.azurerm_key_vault_secret.dynatrace_token.value}"

aks_infra_subscription_id = "8cbc6f36-7c56-4963-9d36-739db5d00b27"
