elasticsearch:
  hosts:
    ccd-data-0:
      ansible_host: 10.112.153.7
      ansible_hostname: ccd-data-0
      fault_domain: 0
      update_domain: 0
    ccd-data-1:
      ansible_host: 10.112.153.6
      ansible_hostname: ccd-data-1
      fault_domain: 1
      update_domain: 1
    ccd-data-2:
      ansible_host: 10.112.153.9
      ansible_hostname: ccd-data-2
      fault_domain: 1
      update_domain: 2
    ccd-data-3:
      ansible_host: 10.112.153.5
      ansible_hostname: ccd-data-3
      fault_domain: 0
      update_domain: 3